### ISSUE TITLE
Document new templates default includeDate option

### ISSUE THREAD

**Issue by jviotti** [jsdoc3/jsdoc3.github.com#103]
As described in https://github.com/jsdoc3/jsdoc/issues/910, I included a new `templates.default.includeDate` option that allows the user to disable the current date from the default template.

The PR (https://github.com/jsdoc3/jsdoc/pull/916) has been merged, so it'd be nice if this new option can get documented.

- If `templates.default.includeDate` is omitted, the default behaviour is preserved and the date is shown.
- If `templates.default.includeDate` is true, the default behaviour is preserved and the date is shown.
- If `templates.default.includeDate` is false, the current date is not shown.

**Comment by hegemonic** [comment]
Fixed on master.
