### ISSUE TITLE
Redundant display of the member's type

### ISSUE THREAD

**Issue by flogit** [jsdoc3/jsdoc3.github.com#104]
For the members of classes, the type is displayed as the signature, example :

(readonly) width :number

And this type (number in this example) is also displayed below in the "Type" section. This display is redundant (and make hard to read documentation with a lot of members).

Could we remove the "Type" section if this type is already displayed in the signature ?

Florian (sorry for my english!)

**Comment by flogit** [comment]
And a very beautiful illustration :
![member_type_redundant](https://cloud.githubusercontent.com/assets/2523734/6203021/772fc1ec-b50a-11e4-8cbe-c7f7c3cd8102.png)

**Comment by hegemonic** [comment]
@flogit I'm open to this suggestion, but can you please refile this issue in the [main JSDoc repo](https://github.com/jsdoc3/jsdoc/issues)? This repo is for the JSDoc website.

**Comment by flogit** [comment]
Yep sorry, I post again in the correct repo !
