### ISSUE TITLE
output index.html is not linking to methods or files

### ISSUE THREAD

**Issue by tykayn** [jsdoc3/jsdoc3.github.com#114]
i have run the jsdoc command on several js files from my works/ folder,
and got some files exported data in out/
command in bash: 
__jsdoc works/*.js --verbose__

but all i get in out/index.html is:

Home | Home (menu on the right)
Documentation generated by JSDoc 3.3.2 on Thu Jun 18 2015 16:47:56 GMT+0200 (CEST)

i also have an html file for each js file evaluated by jsdoc, with the content of my js file.
but i dont have the methods listed in the menu, juste Home, like in index.html

i expected some different content, what did i do wrong ?

**Comment by hegemonic** [comment]
It sounds like your JS files don't have the kind of comments that JSDoc is expecting. Try looking at the examples on [Use JSDoc](http://usejsdoc.org/) to see how JSDoc expects you to tag your documentation.

(Also, just a heads up: This is the repository for JSDoc's documentation. In the future, please send questions to the [jsdoc-users mailing list](http://groups.google.com/group/jsdoc-users). If you find a bug or have a feature request, you can file a new issue at [jsdoc3/jsdoc](https://github.com/jsdoc3/jsdoc). Thanks!)
