### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by Maninacan** [jsdoc3/jsdoc3.github.com#134]
On line 213 of node_modules/jsdoc/lib/jsdoc/src/astnode.js I'm getting the error:

```
node_modules/jsdoc/lib/jsdoc/src/astnode.js:215
                var key = prop.key.name;
                                  ^

TypeError: Cannot read property 'name' of undefined
    at /Users/jonaaron/Projects/record-ordinances/node_modules/jsdoc/lib/jsdoc/src/astnode.js:215:35
```

So prop.key is showing up undefined for one of the properties.  Not sure which property it is nor whether the property is expected to be there by design, but I've created my own workaround that checks the prop.key value and only runs the code if truthy.  See the following:

Original code at node_modules/jsdoc/lib/jsdoc/src/astnode.js:213
```
node.properties.forEach(function(prop) {
	var key = prop.key.name;
	// preserve literal values so that the JSON form shows the correct type
	if (prop.value.type === Syntax.Literal) {
		tempObject[key] = prop.value.value;
	}
	else {
		tempObject[key] = nodeToValue(prop);
	}
});
```

Modified code
```
node.properties.forEach(function(prop) {
	if (prop.key) {
		var key = prop.key.name;
		// preserve literal values so that the JSON form shows the correct type
		if (prop.value.type === Syntax.Literal) {
			tempObject[key] = prop.value.value;
		}
		else {
			tempObject[key] = nodeToValue(prop);
		}
	}
});
```

This seems to be working, but not sure whether it will break something else.

**Comment by decamun** [comment]
I'm getting this problem as well, but I don't want to use this workaround in a production environment. Do you have any idea yet about what might be causing this?

**Comment by savagetda** [comment]
@decamun I don't.  Right now I'm using the hack I mentioned above.  The project I'm working on is still in initial development and has not yet been released to prod.  It hasn't become the top priority so I've been spending my time on other things.  However, I agree that it is not a good solution for prod.  I'll fork this repo, make the change, and do a PR.

**Comment by talexand** [comment]
This should be closed in favor of https://github.com/jsdoc3/jsdoc3.github.com/issues/134.

**Comment by Nagibaba** [comment]
In my case it was due React prop-types, as I wrote `Component.proptypes`. I changed it to `Component.propTypes` and resolved
