### ISSUE TITLE
Documentation for @lends doesn't match behaviour

### ISSUE THREAD

**Issue by cefn** [jsdoc3/jsdoc3.github.com#140]
Hi,  I reported a bug against JSDoc @lends behaviour apparently not matching the documentation at https://github.com/jsdoc3/jsdoc/issues/1265

The other obvious way to fix the issue in the short term is to change the documentation to match the actual behaviour, although longer term, having methods which are silently lost to documentation is a very bad behaviour in my view. 

Unless there is something wrong with my working test case, (meaning that I have misunderstood the use of @lends somehow) then the documented pseudo-code example at http://usejsdoc.org/tags-lends.html could never work given the current behaviour of jsdoc.

**Comment by hegemonic** [comment]
This was fixed by 1c988699101aa4e0e67b1601f12b4bf7dad5abfc.
