### ISSUE TITLE
Callback does not own return type

### ISSUE THREAD

**Issue by deadmann** [jsdoc3/jsdoc3.github.com#146]
lot of time we use callback only to pass user some data, and then user process them async, but there are also times when  we want user return some data, once they processed the data through their own way, that's when the return type in doc become important...

Like linq libraries, or my case, or etc...., so the intellisense can/will guide the user through introducing the return value, if the user missed it by mistake, something i did a lot.

**Comment by hegemonic** [comment]
I'm not sure I understand what you're asking for. JSDoc provides a way to document the values that are passed to a callback; see the [`@callback` tag docs](http://usejsdoc.org/tags-callback.html) for details. However, I can't promise you that your IDE will understand this syntax.

**Comment by deadmann** [comment]
No, i look for return value of that function... you should also tell the user what to return sometimes.

**Comment by deadmann** [comment]
here an e.g. with linq library:

Developer: 
```
var App;
(function (App){
    var EventManager= (function () {
        function EventManager() {
        }
        
        EventManager.handleClick(userMethod){
            if(userMethod($event)){
                 //continue operation
            }
            else{
                 //cancel operation
            }
        }

    }());
    App.EventManager = EventManager;
})(App || App={});
```

User: 
```
EventManager.handleClick(???);
```

Developer:
```
...
/**
*@param userMethod {Function}
*/
...
```

User:
```
EventManager.handleClick(function(???){
...
return ???
});
```

Developer:
```
/**
*@callback EventMethod
*@param $event {EventArgs}
*/

/**
*@param userMethod {EventMethod}
*/
```

User:
```
EventManager.handleClick(/**param $event {EventArgs} */function($event){
...
return ???
});
```

now you see? still return type is unspecified and user cannot understand if he need to return something or not and what kind of data it should be!
