### ISSUE TITLE
create release tags for milestones

### ISSUE THREAD

**Issue by nicholascloud** [jsdoc3/jsdoc3.github.com#59]
Hello!

I'm the maintainer for the [jsdoc3-dash](https://github.com/nicholascloud/jsdoc3-dash) docset library. I'm working on some enhancements to the docset generation tasks, and I would like to keep my docset version in sync with the milestone releases for this project, since the documentation is generated based on this project's master branch. Would you please consider creating release tags when milestones have been completed and delivered? That way I can query for milestone versions and update my docset version to match.

Thanks!
N

**Comment by hegemonic** [comment]
I finally got around to tagging the 3.3.0 version of the docs. I'll continue to add new tags from here on out.

Thanks again for maintaining the Dash version of the docs!

**Comment by nicholascloud** [comment]
@hegemonic Submitted a [PR](https://github.com/Kapeli/Dash-User-Contributions/pull/505) for the 3.3.0 docset and updated my project to pull from tags now instead of the master branch. Thanks!
